### ISSUE TITLE
Issue importing/using

### ISSUE THREAD

**Issue by instance-id** [MechaCoder/tinydb-baseClass#21]
Hey there, 
    I seem to be having an issue with trying to use this as a standard package. I used PyCharm to download the package into my virtual environment (in requirements as tinydb_baseClass~=0.5.0), but then when I go to use it as the following:

```python
from tinydb_base import DatabaseBase
```
When I try to run it, I get the following:

```sh
    ﻿from tinydb_base import DatabaseBase
ModuleNotFoundError: No module named 'tinydb_base'
```

Is the discrepancy between the name used for the package itself and the named used to actually import it what might be causing this issue? Perhaps I just need to download it locally and add it manually?

Thanks,
-id

**Comment by instance-id** [comment]
Nevermind, turns out I am just an idiot. It works fine, lol. I forgot I recreated my virtual environment in a different folder but I didn't update my run config to use the right interpreter path. When I ran it straight from the terminal it worked straight away. 👍

**Comment by MechaCoder** [comment]
Hi 

Thank you for using my project, i am glad you got your issue sorted out.
